apiVersion: v1
kind: Secret
metadata:
  name: footsport-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvZm9vdHNwb3J0
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2hlcmU=